import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Lato } from 'next/font/google'


const lato = Lato({
  weight: ['100', '300', '400', '700', '900']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
