import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Poppins } from 'next/font/google'
import { Raleway } from "next/font/google";


const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '900']
})

const raleway = Raleway({
  weight: ['100', '200', '300', '400', '500', '600', '700', '900']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins}, ${raleway}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
